services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "${EXPOSE_NGINX_PORT:-8000}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/php.dockerfile
      args:
        user: ${USER:-laravel}
        uid: ${UID:-1000}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
  queue-worker:
    build:
      context: .
      dockerfile: docker/php/php.dockerfile
      args:
        user: ${USER:-laravel}
        uid: ${UID:-1000}
    working_dir: /var/www/html
    command: php artisan queue:work
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootsecret}
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:
